name: Deploy to Vercel

on:
      push:
            branches:
                  - main # deploy only when pushing to main

jobs:
      deploy:
            runs-on: ubuntu-latest

            env: # <--- Add this block here!
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

            steps:
                  - name: Checkout code
                    uses: actions/checkout@v4

                  - name: Install dependencies
                    run: npm install

                  - name: Build project
                    run: npm run build

                  - name: Deploy to Vercel
                    run: |
                          npm install -g vercel
                          vercel --prod \
                            --token=$VERCEL_TOKEN \
                            --scope=$VERCEL_ORG_ID \
                            --confirm --cwd . \
                            
